=== ARCHIVO: script.js ===
// script.js - ODAM PRODUCCIÓN MUSICAL - SISTEMA OPTIMIZADO
class AudioPlayerSystem{constructor(){this.audioElements=new Map;this.currentPlaying=null;this.isInitialized=false;this.animationFrames=new Map;this.audioContexts=new Map;this.analysers=new Map;this.dataArrays=new Map}
init(){if(this.isInitialized)return;console.log('🎵 Inicializando sistema de audio con ondas en tiempo real...');this.initWebAudioAPI();document.querySelectorAll('audio').forEach(audio=>{const e=audio.id;this.audioElements.set(e,audio);this.setupAudioEvents(e,audio)});this.setupPlayButtons();this.isInitialized=true;console.log('✅ Sistema de audio con ondas inicializado correctamente')}
initWebAudioAPI(){try{this.mainAudioContext=new (window.AudioContext||window.webkitAudioContext);console.log('🔊 Web Audio API inicializada')}catch(e){console.error('❌ Web Audio API no soportada:',e);return false}return true}
setupAudioAnalyser(e,a){if(!this.mainAudioContext)return;try{const t=new (window.AudioContext||window.webkitAudioContext),s=t.createMediaElementSource(a),i=t.createAnalyser();i.fftSize=64;i.smoothingTimeConstant=.8;s.connect(i);i.connect(t.destination);const n=i.frequencyBinCount,c=new Uint8Array(n);this.audioContexts.set(e,t);this.analysers.set(e,i);this.dataArrays.set(e,c)}catch(e){console.warn('⚠️ No se pudo crear analizador para:',e,e)}}
setupAudioEvents(e,a){a.addEventListener('loadedmetadata',()=>{this.setupAudioAnalyser(e,a);this.updateDuration(e)});a.addEventListener('timeupdate',()=>{this.updateProgress(e)});a.addEventListener('ended',()=>{this.resetPlayer(e)});a.addEventListener('error',t=>{console.error(❌ Error cargando audio ${e}:,t);this.showErrorState(e)})}
setupPlayButtons(){document.querySelectorAll('.audio-play-btn').forEach(e=>{e.addEventListener('click',t=>{const s=t.target.closest('.project-card');if(s){const t=s.querySelector('audio');if(t){const s=t.id;this.togglePlay(s)}}})})}
togglePlay(e){const a=this.audioElements.get(e);if(!a){console.error(Audio no encontrado: ${e});return}if(this.currentPlaying&&this.currentPlaying!==a){this.currentPlaying.pause();this.resetPlayer(this.currentPlaying.id)}a.paused?this.playAudio(e,a):this.pauseAudio(e,a)}
playAudio(e,a){const t=this.audioContexts.get(e);t&&t.state==='suspended'&&t.resume();a.play().then(()=>{this.currentPlaying=a;this.setPlayingState(e,true);this.startWaveAnimation(e)}).catch(t=>{console.error('Error al reproducir audio:',t);a.play().catch(e=>{console.error('Error persistente al reproducir:',e)})})}
pauseAudio(e,a){a.pause();this.setPlayingState(e,false);this.stopWaveAnimation(e);this.currentPlaying===a&&(this.currentPlaying=null)}
startWaveAnimation(e){this.stopWaveAnimation(e);const a=this.analysers.get(e),t=this.dataArrays.get(e),s=document.getElementById(e)?.closest('.project-card');if(!a||!t||!s)return this.startSimulatedWaveAnimation(e);const i=s.querySelector('.audio-waveform'),n=i?.querySelectorAll('.wave-bar');if(!n||n.length===0)return;const c=()=>{a.getByteFrequencyData(t);const s=Math.floor(t.length/n.length);n.forEach((a,i)=>{const c=i*s,o=c+s;let d=0;for(let e=c;e<o;e++)d+=t[e];const r=d/s,l=20+r/255*80;a.style.height=l+'%';a.style.opacity=.6+r/255*.4});const i=requestAnimationFrame(c);this.animationFrames.set(e,i)};c()}
startSimulatedWaveAnimation(e){const a=document.getElementById(e)?.closest('.project-card'),t=a?.querySelector('.audio-waveform'),s=t?.querySelectorAll('.wave-bar');if(!s)return;let i=Date.now();const n=()=>{const a=Date.now()-i;s.forEach((t,s)=>{const n=s*100,c=Math.sin((a+n)/200),o=30+Math.abs(c)*70;t.style.height=o+'%';t.style.opacity=.7+Math.abs(c)*.3});const c=requestAnimationFrame(n);this.animationFrames.set(e,c)};n()}
stopWaveAnimation(e){const a=this.animationFrames.get(e);a&&(cancelAnimationFrame(a),this.animationFrames.delete(e));const t=document.getElementById(e)?.closest('.project-card'),s=t?.querySelectorAll('.wave-bar');s&&s.forEach(e=>{e.style.height='20%';e.style.opacity='0.6'})}
setPlayingState(e,a){const t=document.getElementById(e)?.closest('.project-card');if(!t)return;const s=t.querySelector('.audio-play-btn'),i=t.querySelector('.audio-player-mini');s&&(s.innerHTML=a?'<i class="fas fa-pause" aria-hidden="true"></i>':'<i class="fas fa-play" aria-hidden="true"></i>');i&&i.classList.toggle('playing',a)}
updateProgress(e){const a=this.audioElements.get(e),t=document.getElementById(e)?.closest('.project-card');if(!a||!t)return;const s=t.querySelector('.audio-progress'),i=t.querySelector('.audio-time');a.duration&&s&&(s.style.width=a.currentTime/a.duration*100+'%');i&&(i.textContent=${this.formatTime(a.currentTime)} / ${this.formatTime(a.duration)})}
updateDuration(e){const a=this.audioElements.get(e),t=document.getElementById(e)?.closest('.project-card');if(!a||!t)return;const s=t.querySelector('.audio-time');s&&a.duration&&(s.textContent=0:00 / ${this.formatTime(a.duration)})}
resetPlayer(e){const a=this.audioElements.get(e);a&&(a.currentTime=0,this.setPlayingState(e,false),this.stopWaveAnimation(e),this.updateProgress(e))}
showErrorState(e){const a=document.getElementById(e)?.closest('.project-card');if(a){const e=a.querySelector('.audio-time');e&&(e.textContent='Error',e.style.color='#ff6b6b')}}
formatTime(e){if(isNaN(e))return'0:00';const a=Math.floor(e/60),t=Math.floor(e%60);return a+':'+(t<10?'0'+t:t)}
preloadAudios(){this.audioElements.forEach((e,a)=>{e.load()})}}
class ODAMGlobalSystem{constructor(){this.initialized=false;this.currentPage=this.getCurrentPage()}
getCurrentPage(){const e=window.location.pathname;if(e.includes('servicios'))return'servicios';if(e.includes('proyectos'))return'proyectos';if(e.includes('inspiracion'))return'inspiracion';if(e.includes('interaccion'))return'interaccion';if(e.includes('contacto'))return'contacto';return'index'}
async init(){if(this.initialized)return;console.log(🎵 ODAM - Inicializando página: ${this.currentPage});try{this.initMobileMenu();this.initSmoothScroll();this.initHeaderScroll();this.initAnimations();if(this.currentPage==='proyectos'){window.audioSystem=new AudioPlayerSystem;window.audioSystem.init();setTimeout(()=>{window.audioSystem.preloadAudios()},1e3)}
this.initPageSpecificSystems();this.initialized=true;console.log('✅ ODAM - Sistema completamente inicializado')}catch(e){console.error('❌ Error durante la inicialización:',e)}}
initMobileMenu(){const e=document.getElementById('site-nav-toggle'),t=document.getElementById('site-nav');if(!e||!t)return;e.addEventListener('click',function(s){s.stopPropagation();const i=this.getAttribute('aria-expanded')==='true';this.setAttribute('aria-expanded',String(!i));t.classList.toggle('open');document.body.style.overflow=i?'auto':'hidden'});t.querySelectorAll('a').forEach(e=>{e.addEventListener('click',()=>{t.classList.remove('open');e.setAttribute('aria-expanded','false');document.body.style.overflow='auto'})});document.addEventListener('click',t=>{t.classList.contains('open')&&!t.contains(t.target)&&!e.contains(t.target)&&(t.classList.remove('open'),e.setAttribute('aria-expanded','false'),document.body.style.overflow='auto')})}
initSmoothScroll(){document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener('click',function(e){const t=this.getAttribute('href');if(t==='#')return;e.preventDefault();const s=document.querySelector(t);s&&s.scrollIntoView({behavior:'smooth',block:'start'})})})}
initHeaderScroll(){const e=document.querySelector('header');if(!e)return;let t;window.addEventListener('scroll',()=>{e.classList.toggle('scrolled',window.scrollY>50);clearTimeout(t);t=setTimeout(()=>{e.style.transition='all 0.3s ease'},10)})}
initAnimations(){const e={threshold:.1,rootMargin:'0px 0px -50px 0px'},t=new IntersectionObserver(e=>{e.forEach(e=>{e.isIntersecting&&e.target.classList.add('show')})},e);document.querySelectorAll('.fade-in').forEach(e=>{t.observe(e)})}
initPageSpecificSystems(){switch(this.currentPage){case'inspiracion':this.initBibleVerses();break;case'interaccion':this.initStatsSystem();break}}
initBibleVerses(){const e=document.getElementById('bible-verse');if(!e)return;const t=[{text:"Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.",reference:"Juan 3:16"},{text:"El Señor es mi pastor; nada me faltará.",reference:"Salmos 23:1"},{text:"Echad toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros.",reference:"1 Pedro 5:7"}];function s(){const s=t[Math.floor(Math.random()*t.length)];e.innerHTML=<div class="verse-content"><div class="verse-text">"${s.text}"</div><div class="verse-reference">${s.reference}</div></div>}
s();const i=document.getElementById('new-verse-btn');i&&i.addEventListener('click',s)}
initStatsSystem(){console.log('📊 Sistema de estadísticas listo')}}
document.addEventListener('DOMContentLoaded',function(){if(window.odamSystem)return;window.odamSystem=new ODAMGlobalSystem;window.odamSystem.init()});if(!Element.prototype.closest){Element.prototype.closest=function(e){let t=this;do{if(t.matches(e))return t;t=t.parentElement||t.parentNode}while(t!==null&&t.nodeType===1);return null}}
window.addEventListener('load',function(){if(typeof particlesJS!=='undefined'&&document.getElementById('particles-js')){particlesJS('particles-js',{particles:{number:{value:40,density:{enable:true,value_area:800}},color:{value:"#c8a25f"},shape:{type:"circle"},opacity:{value:.3,random:true},size:{value:3,random:true},line_linked:{enable:true,distance:150,color:"#c8a25f",opacity:.2,width:1},move:{enable:true,speed:2,direction:"none",random:true,straight:false,out_mode:"out"}},interactivity:{detect_on:"canvas",events:{onhover:{enable:true,mode:"grab"},onclick:{enable:true,mode:"push"}}},retina_detect:true})}});
=== FIN ARCHIVO ===
