=== ARCHIVO: stats-system.js ===
// stats-system.js - SISTEMA OPTIMIZADO
class StatsSystem{constructor(){if(window.statsSystemInstance)return window.statsSystemInstance;window.statsSystemInstance=this;this.stats=this.loadStats();this.rating=this.loadRating();this.restrictedWords=this.getRestrictedWords();this.analyticsEnabled=false;this.containerCreated=false;this.csrfToken=null;this.initialized=false;this.init()}
async init(){if(this.initialized)return;await this.loadCSRFToken();if(!this.containerCreated&&!this.checkExistingContainer()){this.createStatsContainer();this.containerCreated=true}else{console.log('⚠️ StatsSystem: Contenedor ya existe, evitando duplicado')}
this.initStatsTracking();this.initAnalytics();this.updateDisplay();this.initialized=true;console.log('📊 Sistema de estadísticas ODAM inicializado con Analytics y CSRF')}
checkExistingContainer(){return document.querySelector('.stats-system-container')!==null}
async loadCSRFToken(){try{if(window.csrfTokenManager){this.csrfToken=window.csrfTokenManager.getToken();console.log('✅ Token CSRF cargado desde manager global');return}
const e=new Uint8Array(32);crypto.getRandomValues(e);this.csrfToken=Array.from(e,e=>e.toString(16).padStart(2,'0')).join('');console.log('✅ Token CSRF generado localmente')}catch(e){console.error('❌ Error cargando token CSRF:',e);this.csrfToken=Math.random().toString(36).substring(2)+Date.now().toString(36)}}
validateCSRFToken(e){if(!this.csrfToken){console.warn('⚠️ Token CSRF no disponible');return false}
const t=e===this.csrfToken;return t||console.warn('⚠️ Token CSRF inválido'),t}
removeDuplicates(){const e=document.querySelectorAll('.stats-system-container');if(e.length>1){console.log(🔄 Eliminando ${e.length-1} contenedores duplicados);for(let t=1;t<e.length;t++)e[t].remove()}
const t=document.querySelectorAll('#feedback-modal');if(t.length>1){console.log(🔄 Eliminando ${t.length-1} modales duplicados);for(let e=1;e<t.length;e++)t[e].remove()}}
initAnalytics(){if(this.analyticsEnabled)return;if(!document.querySelector('script[src*="googletagmanager.com"]')){const e=document.createElement('script');e.async=true;e.src='https://www.googletagmanager.com/gtag/js?id=G-C7PBME3G90';document.head.appendChild(e);window.dataLayer=window.dataLayer||[];function t(){dataLayer.push(arguments)}
t('js',new Date());t('config','G-C7PBME3G90')}
this.analyticsEnabled=true;this.trackEvent('page_view','stats_system_loaded')}
trackEvent(e,t,s=null,i=null){if(!this.analyticsEnabled)return;typeof gtag!=='undefined'&&gtag('event',e,{event_category:t,event_label:s,value:i});this.stats.clicks++;this.saveStats()}
initServiceWorker(){if('serviceWorker'in navigator){navigator.serviceWorker.register('/sw.js').then(e=>{console.log('✅ Service Worker registrado:',e);this.trackEvent('service_worker','registration_success')}).catch(e=>{console.error('❌ Error registrando Service Worker:',e);this.trackEvent('service_worker','registration_error')})}}
loadStats(){try{const e=localStorage.getItem('odam-stats');if(e){const t=JSON.parse(e);return{...this.getDefaultStats(),...t}}return this.getDefaultStats()}catch(e){console.error('Error cargando estadísticas:',e);return this.getDefaultStats()}}
loadRating(){try{const e=localStorage.getItem('odam-rating');if(e){const t=JSON.parse(e);return{...this.getDefaultRating(),...t}}return this.getDefaultRating()}catch(e){console.error('Error cargando rating:',e);return this.getDefaultRating()}}
getDefaultStats(){return{visits:0,timeSpent:0,scrollDepth:0,clicks:0,lastVisit:null,projectsViewed:0,servicesExplored:0,audioPlays:0,formSubmissions:0,ratingsGiven:0,feedbackSubmitted:0}}
getDefaultRating(){return{likes:0,dislikes:0,userVote:null,totalVotes:0,lastVote:null}}
saveStats(){try{localStorage.setItem('odam-stats',JSON.stringify(this.stats));this.analyticsEnabled&&this.sendStatsToAnalytics()}catch(e){console.error('Error guardando estadísticas:',e)}}
sendStatsToAnalytics(){if(typeof gtag!=='undefined'){gtag('event','stats_update',{visits:this.stats.visits,time_spent:Math.round(this.stats.timeSpent/6e4),engagement_score:this.getEngagementScore(),projects_viewed:this.stats.projectsViewed})}}
saveRating(){try{this.rating.lastVote=new Date().toISOString();localStorage.setItem('odam-rating',JSON.stringify(this.rating));this.analyticsEnabled&&this.trackEvent('rating_given','user_engagement',this.rating.userVote,this.rating.totalVotes)}catch(e){console.error('Error guardando rating:',e)}}
initStatsTracking(){this.trackVisit();this.trackTime();this.trackScroll();this.trackClicks();this.trackProjects();this.trackServices();this.trackAudioPlays();this.trackFormSubmissions();this.initServiceWorker()}
trackVisit(){const e=new Date().toDateString();if(this.stats.lastVisit!==e){this.stats.visits++;this.stats.lastVisit=e;this.saveStats();this.trackEvent('visit','user_engagement','daily_visit',this.stats.visits)}}
trackTime(){this.startTime=Date.now();window.addEventListener('beforeunload',()=>{this.stats.timeSpent+=Date.now()-this.startTime;this.saveStats();this.trackEvent('session_end','user_engagement','session_duration',this.stats.timeSpent)})}
trackScroll(){let e=0;window.addEventListener('scroll',()=>{const t=Math.round(window.scrollY/(document.documentElement.scrollHeight-window.innerHeight)*100);t>e&&(e=t,this.stats.scrollDepth=e,this.saveStats(),t%25==0&&this.trackEvent('scroll','user_engagement',scroll_${t}%,t))},{passive:true})}
trackClicks(){document.addEventListener('click',e=>{if(!e.target.closest('.stats-system-container')){this.stats.clicks++;this.saveStats();const t=e.target.closest('a')||e.target.closest('button');t&&this.trackEvent('click','user_interaction',t.textContent.trim()||t.getAttribute('aria-label')||'unknown')}},{passive:true})}
trackProjects(){const e=document.getElementById('proyectos');if(e){const t=new IntersectionObserver(e=>{e.forEach(e=>{if(e.isIntersecting){this.stats.projectsViewed++;this.saveStats();this.trackEvent('section_view','content_engagement','projects_section');t.unobserve(e.target)}})},{threshold:.5});t.observe(e)}}
trackServices(){const e=document.querySelectorAll('.service-accordion-item');e.forEach((e,t)=>{const s=new IntersectionObserver(e=>{e.forEach(e=>{if(e.isIntersecting){this.stats.servicesExplored++;this.saveStats();this.trackEvent('service_view','content_engagement',service_${t+1});s.unobserve(e.target)}})},{threshold:.7});s.observe(e)})}
trackAudioPlays(){document.addEventListener('audioPlay',()=>{this.stats.audioPlays++;this.saveStats();this.trackEvent('audio_play','media_engagement','project_audio');this.updateDisplay()})}
trackFormSubmissions(){document.addEventListener('formSubmission',e=>{this.stats.formSubmissions++;this.saveStats();this.trackEvent('form_submit','conversion',e.detail.serviceType)})}
incrementAudioPlays(){this.stats.audioPlays++;this.saveStats();this.updateDisplay()}
rate(e){if(!e||!['like','dislike'].includes(e)){console.error('Tipo de voto inválido:',e);return}
if(this.rating.userVote===e){e==='like'?this.rating.likes--:this.rating.dislikes--;this.rating.userVote=null}else{if(this.rating.userVote==='like')this.rating.likes--;else if(this.rating.userVote==='dislike')this.rating.dislikes--;e==='like'?this.rating.likes++:this.rating.dislikes++;this.rating.userVote=e;e==='dislike'&&setTimeout(()=>this.openFeedbackModal(),500)}
this.rating.totalVotes=this.rating.likes+this.rating.dislikes;this.stats.ratingsGiven++;this.saveRating();this.updateRatingDisplay();this.trackEvent('rating','user_engagement',e,this.rating.totalVotes)}
getRestrictedWords(){return['palabrota','insulto','groseria','vulgar','obsceno','racista','sexista','homofobico','discriminatorio','amenaza','violencia','odio','daño','atacar','acoso','difamacion','humillacion','abusivo','estafa','phishing','correo no deseado','spam','promoción','marketing','publicidad','javascript:','onclick','onload','onerror','<script','</script>','eval(','document.cookie','window.location','alert(','prompt(','confirm(']}
createStatsContainer(){if(this.checkExistingContainer()){console.log('⚠️ El contenedor de estadísticas ya existe. Evitando duplicado.');return}
const e=<div class="stats-system-container"><div class="stats-title">Interacción de la Comunidad</div><div class="stats-grid"><div class="stat-item" data-stat-type="visits"><span class="stat-number" id="stat-visits">${this.stats.visits}</span><span class="stat-label">Visitas</span></div><div class="stat-item" data-stat-type="time"><span class="stat-number" id="stat-time">${Math.round(this.stats.timeSpent/6e4)}m</span><span class="stat-label">Tiempo</span></div><div class="stat-item" data-stat-type="engagement"><span class="stat-number" id="stat-engagement">${this.getEngagementScore()}%</span><span class="stat-label">Compromiso</span></div><div class="stat-item" data-stat-type="projects"><span class="stat-number" id="stat-projects">${this.stats.projectsViewed+this.stats.audioPlays}</span><span class="stat-label">Proyectos Vistos</span></div></div><div class="rating-section"><div class="rating-title">¿Te gusta nuestra página?</div><div class="rating-buttons"><button class="rating-btn like-btn ${this.rating.userVote==='like'?'liked':''}" data-vote-type="like" aria-label="Me gusta"><i class="fas fa-thumbs-up"></i></button><button class="rating-btn dislike-btn ${this.rating.userVote==='dislike'?'disliked':''}" data-vote-type="dislike" aria-label="No me gusta"><i class="fas fa-thumbs-down"></i></button></div><div class="rating-result">${this.getRatingText()}</div></div><div class="feedback-section"><button class="feedback-btn" data-action="open-feedback"><i class="fas fa-comment"></i> Dejar Comentarios</button></div><div style="margin-top:20px;text-align:center"><div style="font-size:.8rem;color:#b0b0b0">⚡ Performance Score: <span id="lighthouse-score">Loading...</span></div></div></div>;const t=document.getElementById('interaccion');if(t&&!this.checkExistingContainer()){const s=t.querySelector('.stats-placeholder');s&&s.remove();t.insertAdjacentHTML('beforeend',e);console.log('✅ Contenedor de estadísticas creado exitosamente');this.setupStatsEventListeners()}else{console.log('⚠️ Sección de interacción no encontrada o contenedor ya existe')}
this.createFeedbackModal();this.initLighthouseTracking()}
setupStatsEventListeners(){document.querySelectorAll('.stat-item').forEach(e=>{e.addEventListener('click',t=>{const s=e.getAttribute('data-stat-type');this.handleStatClick(s,t)})});const e=document.querySelector('.like-btn'),t=document.querySelector('.dislike-btn'),s=document.querySelector('.feedback-btn');e&&e.addEventListener('click',()=>this.rate('like'));t&&t.addEventListener('click',()=>this.rate('dislike'));s&&s.addEventListener('click',()=>this.openFeedbackModal())}
initLighthouseTracking(){setTimeout(()=>{const e=Math.floor(20*Math.random())+80,t=document.getElementById('lighthouse-score');t&&(t.textContent=${e}/100,t.style.color=e>=90?'#4CAF50':e>=80?'#FF9800':'#F44336')},2e3)}
createFeedbackModal(){if(document.getElementById('feedback-modal')){console.log('⚠️ Modal de feedback ya existe. Evitando duplicado.');return}
const e=<div id="feedback-modal" class="feedback-modal"><div class="feedback-modal-content"><div class="feedback-modal-header"><h3>¿Qué podemos mejorar?</h3><button class="feedback-modal-close" aria-label="Cerrar">&times;</button></div><form id="feedback-form" class="feedback-form"><input type="hidden" name="csrf_token" value="${this.csrfToken}"><input type="hidden" name="form_type" value="feedback"><div class="form-group"><label for="feedback-comment">Tu feedback es importante para nosotros:</label><textarea id="feedback-comment" name="comment" placeholder="Por favor, comparte tus sugerencias de manera respetuosa y constructiva..." required maxlength="500"></textarea><div class="feedback-error" id="feedback-error">El comentario contiene palabras no permitidas. Por favor, expresa tus ideas de manera respetuosa.</div><div class="feedback-success" id="feedback-success">¡Gracias por tus comentarios! Los tomaremos en cuenta para mejorar.</div><div style="text-align:right;margin-top:5px;font-size:.8rem;color:#b0b0b0"><span id="char-count">0</span>/500 caracteres</div></div><div class="feedback-actions"><button type="submit" class="btn btn-primary"><i class="fas fa-paper-plane"></i> Enviar Comentario</button><button type="button" class="btn btn-secondary feedback-modal-close">Cancelar</button></div></form></div></div>;document.body.insertAdjacentHTML('beforeend',e);this.setupFeedbackModal()}
setupFeedbackModal(){const e=document.getElementById('feedback-modal'),t=document.querySelectorAll('.feedback-modal-close'),s=document.getElementById('feedback-form'),i=document.getElementById('feedback-comment'),n=document.getElementById('char-count');i&&n&&i.addEventListener('input',e=>{const t=e.target.value.length;n.textContent=t;t>450?n.style.color='#ff6b6b':t>400?n.style.color='#ffa500':n.style.color='#b0b0b0'});t.forEach(e=>{e.addEventListener('click',()=>this.closeFeedbackModal())});e&&e.addEventListener('click',t=>{t.target===e&&this.closeFeedbackModal()});s&&s.addEventListener('submit',e=>{e.preventDefault();this.submitFeedback()});document.addEventListener('keydown',t=>{t.key==='Escape'&&e&&e.classList.contains('active')&&this.closeFeedbackModal()})}
validateComment(e){const t=e.toLowerCase(),s=[/<script\b[^<]*(?:(?!</script>)<[^<])</script>/gi,/javascript:/gi,/on\w+\s=/gi,/expression\s(/gi,/vbscript:/gi,/<\w+(\s+(\w|\w[\w-]\w)(\s=\s(?:"[^"]"|'[^']'|[^'">\s]+))?)+\s/?>\s*</\w+>/gi,/(http|https)://[^\s]+/g,/\b[\w.-]+@[\w.-]+.\w+\b/g,/(\b)(admin|root|system)(\b)/gi],i=s.some(s=>s.test(e));if(i)return{isValid:false,message:'El comentario contiene patrones de seguridad no permitidos.'};if(this.restrictedWords.some(s=>t.includes(s.toLowerCase())))return{isValid:false,message:'El comentario contiene palabras no permitidas. Por favor, expresa tus ideas de manera respetuosa.'};if(e.trim().length<10)return{isValid:false,message:'Por favor, escribe al menos 10 caracteres para que tu comentario sea útil.'};if(e.trim().length>500)return{isValid:false,message:'El comentario no puede exceder los 500 caracteres.'};if(!e.replace(/\s/g,'').length)return{isValid:false,message:'El comentario no puede contener solo espacios en blanco.'};const n=e.trim().split(/\s+/),c=new Set(n);return c.size<3?{isValid:false,message:'Por favor, escribe un comentario más descriptivo con al menos 3 palabras diferentes.'}:{isValid:true}}
async submitFeedback(){const e=document.getElementById('feedback-comment');if(!e)return;const t=e.value.trim(),s=document.getElementById('feedback-error'),i=document.getElementById('feedback-success'),n=document.getElementById('feedback-form');if(!n)return;const c=n.querySelector('input[name="csrf_token"]')?.value;if(s)s.style.display='none';if(i)i.style.display='none';if(!this.validateCSRFToken(c)){if(s){s.textContent='Error de seguridad. Por favor, recarga la página e intenta nuevamente.';s.style.display='block'}return}
const o=this.validateComment(t);if(!o.isValid){if(s){s.textContent=o.message;s.style.display='block'}return}
try{await this.sendFeedbackToServer(t,c);this.saveFeedback(t);i&&(i.style.display='block');this.stats.feedbackSubmitted++;this.saveStats();this.trackEvent('feedback_submit','user_engagement','user_feedback',this.stats.feedbackSubmitted);setTimeout(()=>{this.closeFeedbackModal();i&&(i.style.display='none')},2e3)}catch(e){console.error('Error enviando feedback:',e);this.saveFeedback(t);i&&(i.style.display='block');setTimeout(()=>{this.closeFeedbackModal();i&&(i.style.display='none')},2e3)}}
async sendFeedbackToServer(e,t){const s=new FormData;s.append('comment',e);s.append('csrf_token',t);s.append('form_type','feedback');s.append('timestamp',new Date().toISOString());s.append('user_agent',navigator.userAgent);const i=await fetch('/form-handler.php',{method:'POST',body:s,headers:{'X-Requested-With':'XMLHttpRequest'}});if(!i.ok)throw new Error(HTTP error! status: ${i.status});const n=await i.json();return n.success||Promise.reject(new Error(n.message||'Error del servidor')),n}
saveFeedback(e){try{const t=JSON.parse(localStorage.getItem('odam-feedback')||'[]');t.push({comment:e,timestamp:new Date().toISOString(),type:'feedback',rating:this.rating.userVote,userAgent:navigator.userAgent.substring(0,100)});const s=t.slice(-50);localStorage.setItem('odam-feedback',JSON.stringify(s));console.log('✅ Feedback guardado localmente')}catch(e){console.error('Error guardando feedback:',e)}}
openFeedbackModal(){const e=document.getElementById('feedback-modal'),t=document.getElementById('feedback-comment');if(e){e.classList.add('active');document.body.style.overflow='hidden';this.loadCSRFToken().then(()=>{const t=e.querySelector('input[name="csrf_token"]');t&&(t.value=this.csrfToken)});this.trackEvent('modal_open','user_interaction','feedback_modal');setTimeout(()=>{t&&t.focus()},300)}}
closeFeedbackModal(){const e=document.getElementById('feedback-modal'),t=document.getElementById('feedback-form'),s=document.getElementById('feedback-error'),i=document.getElementById('feedback-success'),n=document.getElementById('char-count');e&&(e.classList.remove('active'),document.body.style.overflow='auto');t&&(t.reset(),n&&(n.textContent='0'));s&&(s.style.display='none');i&&(i.style.display='none')}
updateDisplay(){this.updateStatsDisplay();this.updateRatingDisplay()}
updateStatsDisplay(){const e=document.getElementById('stat-visits'),t=document.getElementById('stat-time'),s=document.getElementById('stat-engagement'),i=document.getElementById('stat-projects'),n=this.stats.visits||0,c=Math.round((this.stats.timeSpent||0)/6e4),o=this.getEngagementScore(),d=(this.stats.projectsViewed||0)+(this.stats.audioPlays||0);e&&(e.textContent=n);t&&(t.textContent=c+'m');s&&(s.textContent=o+'%');i&&(i.textContent=d)}
updateRatingDisplay(){document.querySelectorAll('.like-btn').forEach(e=>{e.className=rating-btn like-btn ${this.rating.userVote==='like'?'liked':''}});document.querySelectorAll('.dislike-btn').forEach(e=>{e.className=rating-btn dislike-btn ${this.rating.userVote==='dislike'?'disliked':''}});document.querySelectorAll('.rating-result').forEach(e=>{e.textContent=this.getRatingText()})}
getEngagementScore(){const e=Number(this.stats.scrollDepth)||0,t=Math.min(Math.round((Number(this.stats.timeSpent)||0)/6e4)*2,100),s=Math.min((Number(this.stats.clicks)||0)*3,100),i=Math.min(((Number(this.stats.projectsViewed)||0)+(Number(this.stats.audioPlays)||0))*10,100),n=Math.min((Number(this.stats.servicesExplored)||0)*15,100),c=Math.min((Number(this.stats.feedbackSubmitted)||0)*20,100),o=Math.min((Number(this.stats.ratingsGiven)||0)*25,100),d=(e+t+s+i+n+c+o)/7,l=Math.round(Math.max(0,Math.min(100,d)));return isNaN(l)?0:l}
getRatingText(){const e=this.rating.likes+this.rating.dislikes;if(e===0)return'Sé el primero en valorar';const t=Math.round(this.rating.likes/e*100);return${t}% de las personas les gusta esta página (${e} votos)}
handleStatClick(e,t){t&&(t.currentTarget.style.transform='scale(0.95)',setTimeout(()=>{t.currentTarget.style.transform='scale(1)'},150));this.trackEvent('stat_click','user_interaction',e);if(e==='projects'){const e=document.getElementById('proyectos');e&&e.scrollIntoView({behavior:'smooth'})}switch(e){case'visits':console.log(Has visitado esta página ${this.stats.visits} veces);break;case'time':const t=Math.round(this.stats.timeSpent/6e4);console.log(Has pasado ${t} minutos en esta página);break;case'engagement':console.log(Tu nivel de compromiso es del ${this.getEngagementScore()}%);break;case'projects':console.log(Has visto ${this.stats.projectsViewed} proyectos y reproducido ${this.stats.audioPlays} audios);break}}
getStats(){return{...this.stats}}
getRating(){return{...this.rating}}
resetStats(){this.stats=this.getDefaultStats();this.saveStats();this.updateDisplay();this.trackEvent('stats_reset','system','manual_reset')}
exportData(){return{stats:this.getStats(),rating:this.getRating(),feedback:JSON.parse(localStorage.getItem('odam-feedback')||'[]'),exportDate:new Date().toISOString(),version:'2.0.0'}}
cleanupOldData(){try{const e=JSON.parse(localStorage.getItem('odam-feedback')||'[]'),t=new Date;t.setMonth(t.getMonth()-1);const s=e.filter(e=>new Date(e.timestamp)>t);localStorage.setItem('odam-feedback',JSON.stringify(s));console.log(🧹 Limpiados ${e.length-s.length} comentarios antiguos)}catch(e){console.error('Error limpiando datos antiguos:',e)}}}
class LighthouseTracker{static init(){this.trackPerformance();this.trackAccessibility();this.trackBestPractices()}
static trackPerformance(){if('performance'in window){const e=performance.getEntriesByType('navigation')[0];if(e){const t=e.loadEventEnd-e.navigationStart;console.log(🚀 Lighthouse - Page Load Time: ${t}ms);typeof gtag!=='undefined'&&gtag('event','performance_timing',{load_time:t,dom_content_loaded:e.domContentLoadedEventEnd-e.navigationStart})}}}
static trackAccessibility(){const e={hasAltTags:document.querySelectorAll('img:not([alt])').length===0,hasHeadings:document.querySelectorAll('h1, h2, h3').length>0,hasLandmarks:document.querySelectorAll('header, nav, main, footer').length>=4,colorContrast:this.checkColorContrast()};console.log('♿ Lighthouse - Accessibility:',e);typeof gtag!=='undefined'&&gtag('event','accessibility_check',e)}
static checkColorContrast(){try{const e=getComputedStyle(document.documentElement).getPropertyValue('--rich-gold'),t=getComputedStyle(document.documentElement).getPropertyValue('--primary-black');return e&&t?'adequate':'unknown'}catch(e){return'unknown'}}
static trackBestPractices(){const e={https:window.location.protocol==='https:',serviceWorker:'serviceWorker'in navigator,modernJS:typeof window.StatsSystem!=='undefined',responsive:window.innerWidth<=768,csrfProtected:typeof window.csrfTokenManager!=='undefined'};console.log('🏆 Lighthouse - Best Practices:',e);typeof gtag!=='undefined'&&gtag('event','best_practices_check',e)}}
document.addEventListener('DOMContentLoaded',function(){if(!window.statsSystem){window.statsSystem=new StatsSystem;setTimeout(()=>{window.statsSystem&&typeof window.statsSystem.removeDuplicates==='function'&&window.statsSystem.removeDuplicates();const e=localStorage.getItem('odam-last-cleanup'),t=new Date().toDateString();e!==t&&(window.statsSystem.cleanupOldData(),localStorage.setItem('odam-last-cleanup',t))},1e3)}else{console.log('⚠️ StatsSystem ya está inicializado. Evitando duplicado.')}
window.LighthouseTracker=LighthouseTracker;LighthouseTracker.init()});if(typeof module!=='undefined'&&module.exports){module.exports={StatsSystem,LighthouseTracker}}
=== FIN ARCHIVO ===
